content = open('src/web/templates/create.html', 'r', encoding='utf-8').read()
print('size:', len(content), 'bytes')
print('tab fields:', content.count('id="tab-fields"'))
print('tab skills:', content.count('id="tab-skills"'))
print('switchTab handles skills:', 'tab-skills' in content)
print('skill-list:', 'id="skill-list"' in content)
print('loadSkills:', 'async function loadSkills' in content)
print('saveCurrentSkill:', 'function saveCurrentSkill' in content)
print('createNewSkill:', 'function createNewSkill' in content)
print('toggleSkillActive:', 'function toggleSkillActive' in content)
print('renderCharTable cols 8:', 'cols =' in content and '\u59d3\u540d' in content)
print('syncCharTableFromValue:', 'syncCharTableFromValue' in content)
print('background key:', "'background'" in content)
print('char-table-scroll:', 'char-table-scroll' in content)
print('div balance:', content.count('<div') == content.count('</div>'))
print('script balance:', content.count('<script>') + content.count('<script ') == content.count('</script>'))
